Clients/MvcAdmin/Controllers/MiscController.cs
using Microsoft.AspNetCore.Mvc;
using MvcAdmin.Models;
using MvcAdmin.ViewModels;

namespace MvcAdmin.Controllers
{
  [Route("[controller]")]
  public class MiscController : Controller
  {
    private readonly IConfiguration _config;
    private readonly MiscServiceModel _miscService;

    public MiscController(IConfiguration config)
    {
      _config = config;
      _miscService = new MiscServiceModel(_config);
    }

    [Route("Index")]
    public IActionResult Index()
    {
      return View();
    }

    [Route("Misc/About", Name = "GetAboutUs")]
    [HttpGet("Aboutus")]
    public async Task<IActionResult> GetAboutUsInfo()
    {
      var aboutInfo = await _miscService.GetAboutUsInfo();
      return View("UpdateAboutUs", aboutInfo);
    }

    [Route("Misc/UpdateAboutUs", Name = "UpdateAboutUs")]
    [HttpPut("UpdateAboutUs")]
    public async Task<IActionResult> UpdateAboutUs(AboutUsViewModel aboutModel)
    {
      if (await _miscService.UpdateAboutUsInfo(aboutModel))
      {
        ViewBag.updateded = true;
        return View("UpdateAboutUs", aboutModel);
      }
      return View("Error!");
    }

    [Route("Misc/ContactInfo", Name = "GetContactInfo")]
    [HttpGet("ContactInfo")]
    public async Task<IActionResult> GetContactInfo()
    {
      var contactInfo = await _miscService.GetContactInfo();
      return View("UpdateContactInfo", contactInfo);
    }

    [Route("Misc/UpdateContactInfo", Name = "UpdateContactInfo")]
    [HttpPut("UpdateContactInfo")]
    public async Task<IActionResult> UpdateContactInfo(ContactInfoViewModel contactModel)
    {
      if (await _miscService.UpdateContactInfo(contactModel))
      {
        ViewBag.updateded = true;
        return View("UpdateContactInfo", contactModel);
      }
      return View("Error!");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View("Error!");
    }
  }
}

Clients/MvcAdmin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MvcAdmin.Models;
using MvcAdmin.ViewModels;

namespace MvcAdmin.Controllers
{
  [Route("[controller]")]
  public class ProductsController : Controller
  {
    private readonly IConfiguration _config;
    private readonly ProductServiceModel _productService;
    public ProductsController(IConfiguration config)
    {
      _config = config;
      _productService = new ProductServiceModel(_config);
    }

    [Route("Index")]
    public IActionResult Index()
    {
      return View();
    }

    [Route("Product/CreateProduct", Name = "CreateProduct")]
    [HttpGet("CreateProduct")]
    public async Task<IActionResult> CreateProduct()
    {
      var product = new PostProductViewModel();
      var categories = await _productService.GetCategories();
      List<SelectListItem> catList = categories.ConvertAll(a =>
      {
        return new SelectListItem()
        {
          Text = a.Name,
          Value = a.Id.ToString()
        };
      });
      ViewBag.Categories = catList;
      return View("CreateProduct", product);
    }

    [Route("Product/PostProduct", Name = "PostProduct")]
    [HttpPost("PostProduct")]
    public async Task<IActionResult> PostProduct(PostProductViewModel productModel)
    {
      var catId = Int32.Parse(productModel.Category.Name!);
      productModel.CategoryId = catId;
      var category = await _productService.GetCategoryById(catId);
      productModel.Category = category;

      // Autofyll
      var prodPic = new ProductPicViewModel
      {
        Id = 1,
        FileName = "img/pic.jpg"
      };
      productModel.ProductPics!.Add(prodPic);

      var prodOverLay = new ProductOverlayViewModel
      {
        Id = 1,
        Name = "Rea",
        ImgUrl = "img/ovLay/rea.jpg"
      };
      productModel.ProductOverlay = prodOverLay;
      productModel.ProductsOverlayId = 1;
      //

      if (await _productService.PostProduct(productModel))
      {
        return View("Index");
      }

      return View("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View("Error!");
    }
  }
}

Clients/MvcAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="~/css/styles.css">
  <title>Deckams Admin</title>
</head>
<body>
  <header>
    <nav>
      <table border="0">
        <tr>
          <td colspan="3">
            <div>
              <img class="logo" src="~/img/site/logo.png" alt="Logo">
            </div>
          </td>
          <td class="infoTd">

          </td>
        </tr>
        <tr>
          <td colspan="4">
            <div>
              <p class="rubrik">Administration</p>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <table border="0">
              <tr>
                <td>
                  <div class="form-control divSpaceBelow divMenu">
                    <a asp-controller="Products" asp-action="Index">PRODUKTER</a> 
                  </div>
                </td>
                <td>
                  <div class="form-control divSpaceBelow divMenu">
                    <a asp-route="GetTheUsers">ANVÄNDARE</a>
                  </div>
                </td>
                <td>
                  <div class="form-control divSpaceBelow divMenu">
                    <a asp-controller="Misc" asp-action="Index">INFO</a>
                  </div> 
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>  

    </nav>
  </header>
  <main>
    @RenderBody()
  </main>
  
</body>
</html>